name: AWS Cost Report to Discord

on:
  schedule:
    - cron: '0 1 * * *' # UTC 1:00 → JST 10:00
  workflow_dispatch:
    inputs:
      date:
        description: '取得する日付 (YYYY-MM-DD形式, 省略可)'
        required: false

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Install AWS CLI
        run: |
          curl "https://awscli.amazonaws.com/awscli-exe-linux-aarch64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          sudo ./aws/install --bin-dir /usr/local/bin --install-dir /usr/local/aws-cli --update
          aws --version

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-region: ap-northeast-1
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Get AWS Cost
        id: get_cost
        run: |
          START_DATE=$(date -d "yesterday" +%Y-%m-%d)
          END_DATE=$(date +%Y-%m-%d)

          COST_JSON=$(aws ce get-cost-and-usage \
            --time-period Start=$START_DATE,End=$END_DATE \
            --granularity DAILY \
            --metrics "UnblendedCost")

          COST_AMOUNT=$(echo $COST_JSON | jq -r '.ResultsByTime[0].Total.UnblendedCost.Amount')
          echo "cost=${COST_AMOUNT}" >> $GITHUB_ENV

          echo "📢 AWSコストレポート"
          echo "昨日 (${START_DATE}) のAWS利用料金: \$${COST_AMOUNT}"

      # - name: Send to Discord
      #   env:
      #     DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
      #   run: |
      #     MESSAGE="📢 AWSコストレポート\n昨日 (${START_DATE}) のAWS利用料金: \$$COST"

      #     curl -H "Content-Type: application/json" -X POST -d \
      #       "{\"content\": \"$MESSAGE\"}" \
      #       $DISCORD_WEBHOOK_URL
