name: "preview & deploy"

on:
  push:
    branches:
      - main
    paths:
      - terraform/**
      - .github/workflows/**
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  TF_VERSION: 1.3.0

defaults:
  run:
    shell: bash
    working-directory: "terraform/"
    
jobs:
  preview:
    name: "Preview"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ env.TF_VERSION }}
      - name: Terraform Fmt
        run: |
          terraform fmt -check
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_IAM_ROLE_ARN }}
          aws-region: ap-northeast-1
      - name: Terraform Init
        run: |
          terraform init -no-color
      - name: Terraform Validate
        run: |
          terraform validate -no-color
      - name: Terraform plan
        run: |
          terraform plan \
            -input=false \
            -no-color \
            -detailed-exitcode
