name: "preview & deploy"

on:
  push:
    branches:
      - main
    paths:
      - terraform/**
      - .github/workflows/**
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  TF_VERSION: 1.3.0

defaults:
  run:
    shell: bash
    working-directory: "terraform/"
    
jobs:
  preview:
    name: "Preview"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ env.TF_VERSION }}
      - name: Terraform Fmt
        run: |
          terraform fmt -check
